[package]
name = "wisard-pt"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
csv = "1.3.0"
rand = "0.8.5"
serde = "1.0.189"
wisard = "0.0.3"
xz2 = "0.1.7"

[dependencies.clap]
version = "4.4.6"
features = ["derive"]
